import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { UserContextProvider } from '@/lib/hooks/user.context';
import Providers from '../providers';
import Footer from '../__components__/footer/footer';
import { Box } from '@mui/material';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ geistSans.variable } ${ geistMono.variable } bg-emerald-500 antialiased`}
      >
        <AppRouterCacheProvider>
          <Providers>
            <UserContextProvider>
              <Box className="flex flex-col mx-auto max-w-screen-sm bg-slate-100 h-screen">
                <Box className="flex-1 overflow-y-auto">{children}</Box>
                <Footer />
              </Box>
            </UserContextProvider>
          </Providers>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
