import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { UserContextProvider } from '@/lib/hooks/user.context';
import Providers from '../providers';
import Footer from '../__components__/footer/footer';
import { Box } from '@mui/material';
import { WalletContextProvider } from '@/lib/hooks/userWallet.context';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          rel="shortcut icon"
          href="/getting-started/logo_short.png"
          type="image/x-icon"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100..900;1,100..900&family=Shadows+Into+Light&display=swap"
          rel="stylesheet"
        />
        <meta charSet="UTF-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        />
        <title>
          C.B football - Live Football Betting on Every League Worldwide
        </title>
        <meta
          name="description"
          content="Btcindia provides best platform to invest and earn profits. "
        />
        <meta
          name="keywords"
          content="btc, Btc, BTC, investment, fixed-deposit, deposit fixed, daily, earning, daily earning, payment, withdrawal, fast, FD"
        />
        <meta name="author" content="btcindia.bond" />

        <meta
          property="og:title"
          content="BTC INDIA - Make your investment count."
        />
        <meta
          property="og:description"
          content="Invest your amount and earn daily"
        />
        <meta
          property="og:image"
          content="https://btcindia.bond/getting-started/logo_short.png"
        />
        <meta
          property="og:url"
          content="https://www.btcindia.bond"
        />
        <meta property="og:type" content="website" />

        <link rel="canonical" href="https://www.btcindia.bond" />

        <link
          rel="icon"
          href="https://www.btcindia.bond/getting-started/logo_short.png"
          type="image/x-icon"
        />

        <meta name="robots" content="index, follow" />
      </head>
      <body
        className={`${ geistSans.variable } ${ geistMono.variable } bg-emerald-500 antialiased`}
      >
        <AppRouterCacheProvider>
          <Providers>
            <UserContextProvider>
              <WalletContextProvider>
                <Box className="flex flex-col mx-auto max-w-screen-sm w-screen bg-slate-100 h-screen">
                  <Box className="flex-1 overflow-y-auto">{children}</Box>
                  <Footer />
                </Box>
              </WalletContextProvider>
            </UserContextProvider>
          </Providers>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
