import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import type { Metadata } from "next";
import "@/app/globals.css";
import { UserContextProvider } from '@/lib/hooks/user.context';
import Providers from '../providers';
import Footer from '../__components__/footer/footer';
import { Box } from '@mui/material';
import { WalletContextProvider } from '@/lib/hooks/userWallet.context';
import Script from 'next/script';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="shortcut icon"
          href="/getting-started/logo_short.png"
          type="image/x-icon"
        />
        <meta charSet="UTF-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        />
        <title>
          BTC - platform where you can invest and earn daily rewards.
        </title>
        <meta
          name="description"
          content="Btcindia provides best platform to invest and earn profits. "
        />
        <meta
          name="keywords"
          content="btc, Btc, BTC, investment, fixed-deposit, deposit fixed, daily, earning, daily earning, payment, withdrawal, fast, FD"
        />
        <meta name="author" content="btcindia.bond" />

        <meta
          property="og:title"
          content="BTC INDIA - Make your investment count."
        />
        <meta
          property="og:description"
          content="Invest your amount and earn daily"
        />
        <meta
          property="og:image"
          content="https://btcindia.bond/getting-started/logo_short.png"
        />
        <meta
          property="og:url"
          content="https://www.btcindia.bond"
        />
        <meta property="og:type" content="website" />

        <link rel="canonical" href="https://www.btcindia.bond" />

        <link
          rel="icon"
          href="https://www.btcindia.bond/getting-started/logo_short.png"
          type="image/x-icon"
        />

        <meta name="robots" content="index, follow" />

      </head>
      <body
        className={` bg-emerald-500`}
      >
        <Script
          src='https://typof.co/smepay/checkout.js'
          strategy='lazyOnload'
        />
        <AppRouterCacheProvider >
          <Providers>
            <UserContextProvider>
              <WalletContextProvider>
                <Box className="flex flex-col mx-auto w-screen max-w-screen-sm bg-slate-100 h-[100dvh]">
                  <Box className="flex-1 overflow-y-auto">{children}</Box>
                  <Footer />
                </Box>
              </WalletContextProvider>
            </UserContextProvider>
          </Providers>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
