import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Providers from '@/app/providers';
import { AdminContextProvider } from "@/lib/hooks/admin.context";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function PublicLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${ geistSans.variable } ${ geistMono.variable } antialiased`}
            >
                <Providers>
                    <AdminContextProvider>
                        {children}
                    </AdminContextProvider>
                </Providers>
            </body>
        </html>
    );
}