import type { Metadata } from "next";
import "@/app/globals.css";
import Providers from '@/app/providers';


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function PublicLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link
                    rel="shortcut icon"
                    href="/getting-started/logo_short.png"
                    type="image/x-icon"
                />
                <meta charSet="UTF-8" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1.0"
                />
                <title>
                    BTC - platform where you can invest and earn daily rewards.
                </title>
                <meta
                    name="description"
                    content="Btcindia provides best platform to invest and earn profits. "
                />
                <meta
                    name="keywords"
                    content="btc, Btc, BTC, investment, fixed-deposit, deposit fixed, daily, earning, daily earning, payment, withdrawal, fast, FD"
                />
                <meta name="author" content="btcindia.bond" />

                <meta
                    property="og:title"
                    content="BTC INDIA - Make your investment count."
                />
                <meta
                    property="og:description"
                    content="Invest your amount and earn daily"
                />
                <meta
                    property="og:image"
                    content="https://btcindia.bond/getting-started/logo_short.png"
                />
                <meta
                    property="og:url"
                    content="https://www.btcindia.bond"
                />
                <meta property="og:type" content="website" />

                <link rel="canonical" href="https://www.btcindia.bond" />

                <link
                    rel="icon"
                    href="https://www.btcindia.bond/getting-started/logo_short.png"
                    type="image/x-icon"
                />

                <meta name="robots" content="index, follow" />
            </head>
            <body className={`max-w-screen-sm`}>
                <Providers>
                    {children}
                </Providers>
            </body>
        </html>
    );
}